s = "    [y][y][g]
         [y][y][g]
         [y][y][g]
[r][r][r][g][g][w][o][o][o][y][b][b]
[r][r][r][g][g][w][o][o][o][y][b][b]
[r][r][r][g][g][w][o][o][o][y][b][b]
         [w][w][b]
         [w][w][b]
         [w][w][b]
"
